on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run JMeter Tests
        uses: ./
        with:
          test-plan-path: ./Git/HW.jmx
          args: ""
          
      - name: Upload Results
        uses: QAInsights/PerfAction@2.0
        with:
          name: jmeter-results
          path: result.jtl
